### ISSUE TITLE
plot is not the same between APDL and Pymapdl_reader

### ISSUE THREAD

**Issue by sdurain** [ansys/pymapdl-reader#336]
### 🤓 Before submitting the issue

- [X] I have visited the [Troubleshooting section](https://mapdl.docs.pyansys.com/troubleshoot/index.html).
- [X] I have searched among the [existing issues](https://github.com/ansys/pymapdl/issues?q=).
- [X] I am using a [Python virtual environment](https://docs.python.org/3/library/venv.html).
- [X] I am using the [latest version of PyMAPDL](https://github.com/ansys/pymapdl/releases) and its dependencies (fully updated virtual environment). You can update them using ``pip install --upgrade --upgrade-strategy eager ansys-mapdl-core`` in your activated virtual environment.

### 🔍 Description of the bug

Hello everybody,

When i plot my rst file with pyansys, it is not the same result as APDL plotting
![apdl](https://github.com/ansys/pymapdl/assets/102184729/9eff2a8b-4b13-44ec-bb45-aabe6ebb3615)

![pyansys](https://github.com/ansys/pymapdl/assets/102184729/f1acb57b-2aa8-43ac-9d6c-c6f68e811204)
Thanks in advance for your help

### 🕵️ Steps To Reproduce

```Python
from ansys.mapdl import reader as pymapdl_reader

model = "C:/test_ansys/MODEL.rst"
result = pymapdl_reader.read_binary(model)
print(result)
result.plot_nodal_solution(0, 'norm', label='Displacement')
```

### 💻 Which Operating System are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📝 PyMAPDL Report

<details><summary>Show the Report!</summary>

```text

# PASTE HERE THE OUTPUT OF `python -c "from ansys.mapdl import core as pymapdl; print(pymapdl.Report())"` here

```
</details>

### 📝 Installed packages

<details><summary>Show the installed packages!</summary>

```text

# PASTE HERE THE OUTPUT OF `python -m pip freeze` here

```
</details>

I have attached the .rst file here: 
[MODEL.txt](https://github.com/ansys/pymapdl/files/13181637/MODEL.txt)

Just change the extension ".txt" to ".rst" ( github doesn't support .rst file)

### 📝 Logger output file

<details><summary>Show the logger output file.</summary>

```text

# PASTE HERE THE CONTENT OF THE LOGGER OUTPUT FILE.

```
</details>

**Comment by mikerife** [comment]
Hi @sdurain I moved this to the PyMAPDL Reader GitHub.  The rst file is compressed and if you search the PyMAPDL GitHub Issues you will see that there is a open issue on compressed results.  The reader is trying to plot compressed values and some are too big hence the 'inf' result.

Prior to solving in Mechanical APDL you can use the /fcomp command to turn off compression for the result file.  Or in WB Mechanical there is an analysis settings to do the same.  For now do that or post-process with PyMAPDL.

Mike

**Comment by sdurain** [comment]
I have added this command in my APDL program :

/FCOMP,RST,0


again the same error.

I transmit you my APDL programs, thanks in advance ! 


[materiaux.txt](https://github.com/ansys/pymapdl-reader/files/13189842/materiaux.txt)
[generate_mesh.txt](https://github.com/ansys/pymapdl-reader/files/13189844/generate_mesh.txt)
[MAIN.txt](https://github.com/ansys/pymapdl-reader/files/13189845/MAIN.txt)

**Comment by mikerife** [comment]
@sdurain watch out as the posted MAIN.txt is inputting a different mesh file.  Once that is corrected for the MAPDL model runs fine.  And PyMAPDL Reader can post-process without any error/issue.

**Comment by sdurain** [comment]
Si if i merge the main.txt and the mesh file there is no errors anymore ?

**Comment by mikerife** [comment]
@sdurain or change the input command in the MAIN.txt to read in generate_mesh.txt,

**Comment by sdurain** [comment]
Ok my bad it was the name of the file in my computer. But still not working in my side : 

![image](https://github.com/ansys/pymapdl-reader/assets/102184729/99fc8b9b-815e-49ab-8ca5-657f4c0ecdfb)

I can open always open my result in ansys APDL, i send you the complete folder with all result file :

https://www.transfernow.net/dl/20231027PThG0FQQ

The program run correctly, i have the modal analysis, pretension analysis etc... In my OUT file, i really don't understand
I run the model with the batch of ansys.

The program that i use:

from ansys.mapdl import reader as pymapdl_reader

model = "C:/test_ansys/job.rst"
result = pymapdl_reader.read_binary(model)
result.plot_nodal_solution(0, 'norm', label='Displacement')
